# Generated by Django 4.1.3 on 2023-07-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdetails',
        ),
    ]
