# Generated by Django 4.1.3 on 2023-07-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
