# Generated by Django 4.1.3 on 2023-07-17 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 17, 8, 27, 20, 788498, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
